In [9]:
import numpy as np
import pandas as pd

In [10]:
url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv"
df = pd.read_csv(url)
df.sample(5)

    age  gender   review education purchased
43   27    Male     Poor        PG        No
40   39    Male     Good    School        No
4    16  Female  Average        UG        No
16   59    Male     Poor        UG       Yes
46   64  Female     Poor        PG        No

In [11]:
df = df.iloc[:,2:]

In [12]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [15]:
X_train

     review education
19     Poor        PG
32  Average        UG
5   Average    School
3      Good        PG
10     Good        UG
20  Average    School
0   Average    School
21  Average        PG
4   Average        UG
34  Average    School
15     Poor        UG
8   Average        UG
27     Poor        PG
36     Good        UG
25     Good    School
40     Good    School
1      Poor        UG
42     Good        PG
24  Average        PG
47     Good        PG
16     Poor        UG
11     Good        UG
18     Good    School
26     Poor        PG
7      Poor    School
38     Good    School
39     Poor        PG
37  Average        PG
43     Poor        PG
23     Good    School
33     Good        PG
41     Good        PG
29  Average        UG
12     Poor    School
22     Poor        PG
2      Good        PG
46     Poor        PG
13  Average    School
17     Poor        UG
45     Poor        PG

In [24]:
from sklearn.preprocessing import OrdinalEncoder

In [25]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [31]:
oe.fit(X_train)

ValueError: could not convert string to float: 'Poor'

In [28]:
X_train = oe.transform(X_train)

IndexError: list index out of range

In [ ]:
X_train

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
le.fit(Y)